// Mock 游戏数据 - 用于在没有后端时展示平台功能
export const mockGames = [
  {
    id: 1,
    title: '赛博朋克 2077',
    slug: 'cyberpunk-2077',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg',
    price: 298,
    currency: 'CNY',
    developer: 'CD Projekt Red',
    publisher: 'CD Projekt',
    releaseDate: '2020-12-10',
    description: '<p>《赛博朋克 2077》是一款以夜之城为背景的开放世界动作角色扮演游戏。夜之城是一个沉迷于权力、魅力和身体改造的大都市，位于美国加利福尼亚州的自由州。你将扮演雇佣兵V，可以选择增加网络、体能和反射三方面技能。</p>',
    averageRating: 4.2,
    reviewCount: 15823,
    genres: [{ id: 1, name: '角色扮演' }, { id: 8, name: '射击' }],
    platforms: [{ id: 1, name: 'Windows' }, { id: 2, name: 'Mac' }],
    tags: [{ id: 1, name: '开放世界' }, { id: 2, name: '赛博朋克' }],
    screenshots: [
      { id: 1, url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/ss_7d2b78cc67e18f2eb3e4b4d8c1e5e4c8b0a0b0d0.jpg' }
    ],
    features: [{ id: 1, name: '单人游戏' }, { id: 2, name: '成就' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '英语' }],
    systemRequirements: { os: 'Windows 10', memory: '12 GB', storage: '70 GB' },
  },
  {
    id: 2,
    title: '艾尔登法环',
    slug: 'elden-ring',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg',
    price: 398,
    currency: 'CNY',
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    releaseDate: '2022-02-25',
    description: '<p>《艾尔登法环》是由宫崎英高与乔治·R·R·马丁共同创作世界观的全新动作角色扮演游戏。在名为"交界地"的广阔世界中冒险，探索丰富多彩的地下城、宏伟的建筑群以及引人入胜的故事。</p>',
    averageRating: 4.8,
    reviewCount: 42156,
    genres: [{ id: 3, name: '角色扮演' }, { id: 1, name: '动作' }],
    platforms: [{ id: 1, name: 'Windows' }],
    tags: [{ id: 3, name: '魂系' }, { id: 4, name: '开放世界' }],
    screenshots: [],
    features: [{ id: 1, name: '单人游戏' }, { id: 3, name: '多人游戏' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '日语' }],
    systemRequirements: { os: 'Windows 10/11', memory: '16 GB', storage: '60 GB' },
  },
  {
    id: 3,
    title: '黑神话：悟空',
    slug: 'black-myth-wukong',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/header.jpg',
    price: 268,
    currency: 'CNY',
    developer: 'Game Science',
    publisher: 'Game Science',
    releaseDate: '2024-08-20',
    description: '<p>《黑神话：悟空》是一款以中国神话为背景的动作角色扮演游戏。你将扮演"天命人"，踏上一段充满挑战与惊奇的西游之旅，在宏大的故事背景下探索这片神话世界。</p>',
    averageRating: 4.9,
    reviewCount: 68932,
    genres: [{ id: 1, name: '动作' }, { id: 3, name: '角色扮演' }],
    platforms: [{ id: 1, name: 'Windows' }],
    tags: [{ id: 5, name: '中国神话' }, { id: 6, name: '单人' }],
    screenshots: [],
    features: [{ id: 1, name: '单人游戏' }, { id: 2, name: '成就' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '英语' }],
    systemRequirements: { os: 'Windows 10 64-bit', memory: '16 GB', storage: '130 GB' },
  },
  {
    id: 4,
    title: 'CS2',
    slug: 'cs2',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg',
    price: 0,
    currency: 'CNY',
    developer: 'Valve',
    publisher: 'Valve',
    releaseDate: '2023-09-27',
    description: '<p>CS2 是 Counter-Strike 的最新版本，基于全新 Source 2 引擎打造，带来了大幅升级的视觉效果、响应性以及革命性的烟雾手雷。</p>',
    averageRating: 4.1,
    reviewCount: 251847,
    genres: [{ id: 8, name: '射击' }],
    platforms: [{ id: 1, name: 'Windows' }, { id: 3, name: 'Linux' }],
    tags: [{ id: 7, name: '免费游玩' }, { id: 8, name: '射击' }],
    screenshots: [],
    features: [{ id: 3, name: '多人游戏' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '英语' }],
    systemRequirements: { os: 'Windows 10', memory: '8 GB', storage: '85 GB' },
  },
  {
    id: 5,
    title: '原神',
    slug: 'genshin-impact',
    coverImage: 'https://upload-bbs.miyoushe.com/upload/2023/08/25/75276539/d32e49beba7756cba33e9264c8ecd498_2218481779226826888.png',
    headerImage: 'https://upload-bbs.miyoushe.com/upload/2023/08/25/75276539/d32e49beba7756cba33e9264c8ecd498_2218481779226826888.png',
    price: 0,
    currency: 'CNY',
    developer: 'miHoYo',
    publisher: 'miHoYo',
    releaseDate: '2020-09-28',
    description: '<p>《原神》是一款由miHoYo开发的开放世界动作角色扮演游戏。游戏拥有开放世界探索、角色成长与多人联机，以及充满动感的元素战斗系统。</p>',
    averageRating: 4.3,
    reviewCount: 98562,
    genres: [{ id: 3, name: '角色扮演' }, { id: 2, name: '冒险' }],
    platforms: [{ id: 1, name: 'Windows' }, { id: 2, name: 'Mac' }],
    tags: [{ id: 7, name: '免费游玩' }, { id: 9, name: '动漫' }],
    screenshots: [],
    features: [{ id: 3, name: '多人游戏' }, { id: 1, name: '单人游戏' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '日语' }],
    systemRequirements: { os: 'Windows 7 SP1 64-bit', memory: '8 GB', storage: '30 GB' },
  },
  {
    id: 6,
    title: '博德之门3',
    slug: 'baldurs-gate-3',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg',
    price: 368,
    currency: 'CNY',
    developer: 'Larian Studios',
    publisher: 'Larian Studios',
    releaseDate: '2023-08-03',
    description: '<p>《博德之门3》是由Larian Studios开发并发行的角色扮演游戏，以D&D规则为基础，带来史诗级的奇幻冒险旅程。</p>',
    averageRating: 4.9,
    reviewCount: 37841,
    genres: [{ id: 3, name: '角色扮演' }],
    platforms: [{ id: 1, name: 'Windows' }, { id: 2, name: 'Mac' }],
    tags: [{ id: 10, name: '回合制' }, { id: 11, name: '奇幻' }],
    screenshots: [],
    features: [{ id: 1, name: '单人游戏' }, { id: 3, name: '多人合作' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '英语' }],
    systemRequirements: { os: 'Windows 10 64-bit', memory: '8 GB', storage: '150 GB' },
  },
  {
    id: 7,
    title: '绝地求生',
    slug: 'pubg',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg',
    price: 0,
    currency: 'CNY',
    developer: 'KRAFTON',
    publisher: 'KRAFTON',
    releaseDate: '2017-12-20',
    description: '<p>《绝地求生》是一款大逃杀类游戏，多名玩家被空降到一个孤岛上，须在不断缩小的安全区域内争夺物资并消灭敌人，最终成为存活的最后一人。</p>',
    averageRating: 3.9,
    reviewCount: 186452,
    genres: [{ id: 8, name: '射击' }],
    platforms: [{ id: 1, name: 'Windows' }],
    tags: [{ id: 7, name: '免费游玩' }, { id: 12, name: '大逃杀' }],
    screenshots: [],
    features: [{ id: 3, name: '多人游戏' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '英语' }],
    systemRequirements: { os: 'Windows 7 64-bit', memory: '8 GB', storage: '40 GB' },
  },
  {
    id: 8,
    title: '文明6',
    slug: 'civilization-6',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/289070/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg',
    price: 198,
    currency: 'CNY',
    developer: 'Firaxis Games',
    publisher: '2K Games',
    releaseDate: '2016-10-21',
    description: '<p>《文明VI》是2K旗下Firaxis Games打造的一款回合制策略游戏。你将引领人类文明，从远古石器时代一路发展到信息时代，书写你的传奇篇章。</p>',
    averageRating: 4.4,
    reviewCount: 89621,
    genres: [{ id: 4, name: '策略' }],
    platforms: [{ id: 1, name: 'Windows' }, { id: 2, name: 'Mac' }, { id: 3, name: 'Linux' }],
    tags: [{ id: 13, name: '回合制策略' }, { id: 14, name: '4X' }],
    screenshots: [],
    features: [{ id: 1, name: '单人游戏' }, { id: 3, name: '多人游戏' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '英语' }],
    systemRequirements: { os: 'Windows 7 64-bit', memory: '8 GB', storage: '15 GB' },
  },
  {
    id: 9,
    title: '欧洲卡车模拟2',
    slug: 'euro-truck-simulator-2',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/227300/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg',
    price: 88,
    currency: 'CNY',
    developer: 'SCS Software',
    publisher: 'SCS Software',
    releaseDate: '2012-10-19',
    description: '<p>踏上横跨欧洲的史诗之旅！驾驶高度精细化的卡车，穿越令人惊叹的风景，将货物运送到目的地。</p>',
    averageRating: 4.6,
    reviewCount: 224815,
    genres: [{ id: 5, name: '模拟' }],
    platforms: [{ id: 1, name: 'Windows' }, { id: 2, name: 'Mac' }, { id: 3, name: 'Linux' }],
    tags: [{ id: 15, name: '驾驶' }, { id: 16, name: '模拟' }],
    screenshots: [],
    features: [{ id: 1, name: '单人游戏' }, { id: 3, name: '多人游戏' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '英语' }],
    systemRequirements: { os: 'Windows 7', memory: '4 GB', storage: '11 GB' },
  },
  {
    id: 10,
    title: '怪物猎人：世界',
    slug: 'monster-hunter-world',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/582010/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/582010/header.jpg',
    price: 248,
    currency: 'CNY',
    developer: 'Capcom',
    publisher: 'Capcom',
    releaseDate: '2018-08-09',
    description: '<p>《怪物猎人：世界》带你踏上全新的狩猎之旅。探索一个充满生命力的生态系统，追踪并猎杀强大的怪物，获取材料打造强力装备。</p>',
    averageRating: 4.7,
    reviewCount: 156843,
    genres: [{ id: 1, name: '动作' }, { id: 3, name: '角色扮演' }],
    platforms: [{ id: 1, name: 'Windows' }],
    tags: [{ id: 17, name: '猎人' }, { id: 18, name: '合作' }],
    screenshots: [],
    features: [{ id: 1, name: '单人游戏' }, { id: 3, name: '多人合作' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '日语' }],
    systemRequirements: { os: 'Windows 7/8/10 64-bit', memory: '8 GB', storage: '48 GB' },
  },
  {
    id: 11,
    title: '只狼：影逝二度',
    slug: 'sekiro',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/814380/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg',
    price: 298,
    currency: 'CNY',
    developer: 'FromSoftware',
    publisher: 'Activision',
    releaseDate: '2019-03-22',
    description: '<p>化身独臂狼忍，在破败没落的战国末期日本展开一段复仇之旅。以精准的剑术和忍术克服险阻，踏上杀戮复仇之路。</p>',
    averageRating: 4.8,
    reviewCount: 89456,
    genres: [{ id: 1, name: '动作' }, { id: 2, name: '冒险' }],
    platforms: [{ id: 1, name: 'Windows' }],
    tags: [{ id: 3, name: '魂系' }, { id: 19, name: '忍者' }],
    screenshots: [],
    features: [{ id: 1, name: '单人游戏' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '日语' }],
    systemRequirements: { os: 'Windows 7 64-bit', memory: '8 GB', storage: '25 GB' },
  },
  {
    id: 12,
    title: 'GTA5',
    slug: 'gta5',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/capsule_616x353.jpg',
    headerImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg',
    price: 148,
    currency: 'CNY',
    developer: 'Rockstar North',
    publisher: 'Rockstar Games',
    releaseDate: '2015-04-14',
    description: '<p>《GTA V》是洛克斯达有史以来规模最大、最具雄心的作品。玩家可以在洛圣都和布雷恩郡的广阔世界中自由探索，扮演三名主角完成交织在一起的精彩故事。</p>',
    averageRating: 4.5,
    reviewCount: 342891,
    genres: [{ id: 1, name: '动作' }, { id: 2, name: '冒险' }],
    platforms: [{ id: 1, name: 'Windows' }],
    tags: [{ id: 20, name: '开放世界' }, { id: 21, name: '犯罪' }],
    screenshots: [],
    features: [{ id: 1, name: '单人游戏' }, { id: 3, name: '多人游戏' }],
    languages: [{ id: 1, name: '简体中文' }, { id: 2, name: '英语' }],
    systemRequirements: { os: 'Windows 10 64 Bit', memory: '8 GB', storage: '72 GB' },
  },
];

export const mockHotGames = mockGames.slice(0, 4);
export const mockNewGames = [mockGames[2], mockGames[5], mockGames[10], mockGames[11]];

export const mockUser = {
  id: 1,
  username: 'demo_user',
  email: 'demo@yunmu.com',
  displayName: '云幕用户',
  avatar: '',
  role: 'USER',
};

export const mockOrders = [
  {
    id: 1,
    orderNo: 'YM202401010001',
    status: 'COMPLETED',
    total: 298,
    createdAt: '2024-01-15T10:30:00Z',
    items: [{ id: 1, game: mockGames[0], price: 298, quantity: 1 }],
  },
  {
    id: 2,
    orderNo: 'YM202401020002',
    status: 'COMPLETED',
    total: 398,
    createdAt: '2024-01-20T14:20:00Z',
    items: [{ id: 2, game: mockGames[1], price: 398, quantity: 1 }],
  },
];

export const mockLibrary = [mockGames[0], mockGames[1]];

export const mockStats = {
  totalUsers: 128456,
  totalGames: 3842,
  totalOrders: 89234,
  totalRevenue: 15678920,
  newUsersToday: 234,
  ordersToday: 156,
  revenueToday: 28460,
  activeUsers: 12345,
};
